# Compass Config
preferred_syntax = :scss
http_path = '/'
css_dir = 'build/css'
sass_dir = 'src/sass'
images_dir = 'build/images'
fonts_dir = 'build/fonts'
relative_assets = true
line_comments = true
